# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/pavel/.local/share/ue/Linux_Unreal_Engine_5.3.2
GAMEPROJECTFILE =/home/pavel/projects/ue/ue5Cpp/ue5Cpp.uproject

TARGETS = \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame \
	ue5Cpp-Linux-DebugGame  \
	ue5Cpp-Linux-Shipping  \
	ue5Cpp \
	ue5CppEditor-Linux-DebugGame  \
	ue5CppEditor-Linux-Shipping  \
	ue5CppEditor\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend ue5CppEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug ue5CppEditor-Linux-Debug


UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

ue5Cpp-Linux-DebugGame:
	 $(PROJECTBUILD) ue5Cpp Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

ue5Cpp-Linux-Shipping:
	 $(PROJECTBUILD) ue5Cpp Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

ue5Cpp:
	 $(PROJECTBUILD) ue5Cpp Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

ue5CppEditor-Linux-DebugGame:
	 $(PROJECTBUILD) ue5CppEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

ue5CppEditor-Linux-Shipping:
	 $(PROJECTBUILD) ue5CppEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

ue5CppEditor:
	 $(PROJECTBUILD) ue5CppEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
